<a href="https://colab.research.google.com/github/manukrmanu/machine-learning/blob/main/heart__.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/heart_missing2.csv')
df

age  sex   cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1  0.0       125   212  0.0      1.0      168      0      1.0   
1      53    1  0.0       140   203  1.0      0.0      155      1      3.1   
2      70    1  0.0       145   174  0.0      1.0      125      1      2.6   
3      61    1  0.0       148   203  0.0      1.0      161      0      0.0   
4      62    0  0.0       138   294  1.0      1.0      106      0      1.9   
...   ...  ...  ...       ...   ...  ...      ...      ...    ...      ...   
1020   59    1  1.0       140   221  0.0      1.0      164      1      0.0   
1021   60    1  0.0       125   258  0.0      0.0      141      1      2.8   
1022   47    1  0.0       110   275  0.0      0.0      118      1      1.0   
1023   50    0  0.0       110   254  0.0      0.0      159      0      0.0   
1024   54    1  0.0       120   188  0.0      1.0      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [ ]:
df.isna().sum()

age          0
sex          0
cp           7
trestbps     0
chol         0
fbs         13
restecg      4
thalach      0
exang        0
oldpeak     11
slope        0
ca           0
thal         0
target       0
dtype: int64

In [ ]:
df.dtypes

age           int64
sex           int64
cp          float64
trestbps      int64
chol          int64
fbs         float64
restecg     float64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [ ]:
x=df['cp'].mode()[0]
df['cp'].fillna(x,inplace=True)
y=df['fbs'].mode()[0]
df['fbs'].fillna(y,inplace=True)
z=df['oldpeak'].mode()[0]
df['oldpeak'].fillna(z,inplace=True)
xx=df['restecg'].max()
df['restecg'].fillna(xx,inplace=True)
df.isna().sum()


age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

In [ ]:
#normalization
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)
x_test

In [ ]:
#modeling
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
k_model=KNeighborsClassifier(n_neighbors=7)
n_model=GaussianNB()
s_model=SVC()
list_model=[k_model,n_model,s_model]

In [ ]:
for i in list_model:
  print("model==",i)
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  y_pred
  print(confusion_matrix(y_test,y_pred))
  print(accuracy_score(y_test,y_pred))
  print("*"*100)



model== KNeighborsClassifier(n_neighbors=7)
[[127  32]
 [ 17 132]]
0.8409090909090909
****************************************************************************************************
model== GaussianNB()
[[118  41]
 [ 18 131]]
0.8084415584415584
****************************************************************************************************
model== SVC()
[[135  24]
 [ 11 138]]
0.8863636363636364
****************************************************************************************************
